# Generated by Django 3.2.4 on 2021-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_field',
            field=models.ImageField(upload_to='gallery_topics/'),
        ),
    ]
